# fly.toml app configuration file generated for email-rag on 2024-10-27T20:16:22+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'email-rag'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 25
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
